; Example .gitconfig file

[alias]
; Retrieve the date of the latest commit in ISO8601 format.
last-date = log -1 --format="%cI"

; Retrieve file names staged for commit
staged = diff --cached --name-only

; Confirm a branch name exists locally (expects a single argument)
verify = rev-parse --quiet --verify

; Capture name of current working branch
current = rev-parse --abbrev-ref HEAD

; Retrieve the name of the default branch of a repository
default = "!sh src/git-default.sh"

; Sync a working branch with repository default branch
sync = "!sh src/git-sync.sh"

; list all branches that have been merged to default branch
list-merged = "!sh src/git-list-merged.sh"

; prune all local branches that have already been merged
prune = "!sh src/git-prune.sh"

; Pretty print commit logs
logs = "!sh src/git-logs.sh"

; unstage a specific file (i.e. undo git add command) (expects a single argument)
unstage = "!sh src/git-unstage.sh"
